#!/bin/bash

scriptpath=$(readlink -f $0)
sockpath=/tmp/ibbrowser
bookmarkspath=${1:-${HOME}/bookmarks}
shift

if [ ! -e "$sockpath" ]; then
    echo "$sockpath does not exist!" > /dev/stderr
    exit 1
fi

if [ ! -d "$bookmarkspath" ]; then
    echo "$bookmarkspath does not exist!" > /dev/stderr
    exit 1
fi

cd "$bookmarkspath" || exit 1
res=$(find . -maxdepth 1 -type d -not -name '.' -printf '%f/\n' -or -type f -printf '%f\n' | dmenu)

echo "res = $res"
if [ -d "$res" ]; then
    $scriptpath "$res"
else
    cat "$res" | netcat -U "$sockpath"
fi
